---
title: Project Management^[Contributions to lectures and practicals by Andrew W. Park,
  John M. Drake and Ana I. Bento]
author: 'Rachel Xu'
date: '05/27/2020'
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```



**Exercise. Copy the MERS data file `cases.csv` and paste it into your working directory.**
```{r}
library(ggplot2)
library(lubridate)
library(plotly)
setwd(".")
```

**Exercise. Create a new script following the prototype we introduced. Your script should load the MERS data and make a plot.**
```{r}
mers <- read.csv("cases.csv", header=TRUE)
head(mers)

class(mers$onset)
mers$onset <- ymd(mers$onset)
class(mers$onset)
day0 <- min(na.omit(mers$onset))
day0
mers$epi.day <- mers$onset - day0

mers_plot <- ggplot(mers) + 
  geom_bar(aes(x=epi.day, fill=country)) +
  labs(x='Epidemic day', y='Case count', title='Global count of MERS cases by date of symptom onset',
       caption="Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")


```

**Make the mers plot interactive**
```{r}
ggplotly(mers_plot)
```

